### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dariocravero**
@webpro thanks for putting this together :) I know that the string clarification might look superfluous but I thought it might save some people some headaches. :)

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @dariocravero, but I think this really just replaces `__VERSION__` (not `'__VERSION__'` including the single quotes).

I like the second update of the readme, so maybe you could update this PR accordingly? :-)

**Comment by dariocravero** [comment]
Glad you like it :). It reads `'__VERSION__'` so that should be outputting
'__VERSION__' in a code block, shouldn't it?

**Comment by webpro** [comment]
Sorry if I'm not understanding correctly, but it doesn't replace quotes, nor does the the placeholder need to be between quotes. So I think it makes sense not to use any in the explanation.

Maybe you can show an example of some documentation in which something similar is explained more clearly?

**Comment by dariocravero** [comment]
Sorry, my bad, now I see what you mean :). I meant to put an example so that people wouldn't think that they can put `var version = __VERSION__` as that would fail to compile and that instead they should've put  `var version = '__VERSION__'` because the version number will be a string at the end of the day :). I fixed that on #6.

**Pull request closed without merging**
