### PR TITLE
Resolve correct versions for dependencies

### PR DESCRIPTION
**Pull request by boris-marinov**
I think this fixes the issue I reported here https://github.com/webpro/versionify/issues/7

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for this. Can you point me to an example that benefits from your fix? I'd like to see it in action.

**Comment by boris-marinov** [comment]
I put together a small example here:
https://dl.dropboxusercontent.com/u/46459223/versionify_test.zip
Basically I have a library that consists of two modules - 'module_one' and 'module_two', where each module has a separate package.json and version, and my aim is to be able to encode each module's version in the library build.

**Comment by webpro** [comment]
Gotcha. Thanks!

**Comment by webpro** [comment]
Released as v1.0.5.

**Pull request merged**
